import './globals.css'
import { ToastProvider } from '../components/Toast/ToastProvider'

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css2?family=Geist+Sans&family=Geist+Mono&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-geistSans antialiased">
        {children}
        <ToastProvider />
      </body>
    </html>
  )
}
